// These icon constants are used to map code to the css classes
// For a full list of icon class names see
// @see https://boxicons.com/
export const ICON = {
  LED_MATRIX: 'grid',
  MENU_HAMBURGER: 'menu',
  SETTINGS: 'settings',
  MENU_HORIZONTAL: 'dots-horizontal',
  MENU_VERTICAL: 'dots-vertical',
  CHECK_CIRCLE: 'check-circle',
  CROSS_CIRCLE: 'x-circle',
  ADD_CIRCLE: 'plus-circle',
  MINUS_CIRCLE: 'minus-circle',
  WARNING: 'error',
  HELP_CIRCLE: 'help-circle',
  INFO_CIRCLE: 'info-circle',
  DANGER: 'error-circle',
  CHECKBOX: 'checkbox',
  CHECKBOX_CHECKED: 'checkbox-checked',
  RADIO_BUTTON: 'circle',
  RADIO_BUTTON_CHECKED: 'check-circle',
  EDIT: 'edit',
  CHECK: 'check',
  CROSS: 'x',
  REFRESH: 'refresh',
  FULLSCREEN: 'fullscreen',
  FULLSCREEN_EXIT: 'exit-fullscreen',
  WIFI: 'wifi',
  WIFI_OFF: 'wifi-off',
  MICROPHONE: 'microphone',
  MICROPHONE_OFF: 'microphone-off',
  VOLUME_MUTE: 'volume-mute',
  VOLUME_DOWN: 'volume-low',
  VOLUME_UP: 'volume-full',
  VOLUME_OFF: 'volume',
  BELL: 'bell',
  BELL_OFF: 'bell-off',
  BELL_RING: 'bell-ring',
  ARROW_LEFT: 'left-arrow',
  ARROW_RIGHT: 'right-arrow',
  ARROW_UP: 'up-arrow',
  ARROW_DOWN: 'down-arrow',
  ROTATE_LEFT: 'rotate-left',
  ROTATE_RIGHT: 'rotate-right',
  CHEVRON_UP: 'chevron-up',
  CHEVRON_DOWN: 'chevron-down',
  CHEVRON_LEFT: 'chevron-left',
  CHEVRON_RIGHT: 'chevron-right',
  EXTERNAL_LINK: 'link-external',
  LOCK: 'lock',
  UNLOCK: 'lock-open',
  DOWNLOAD: 'download',
  UPLOAD: 'upload',
} as const;

export type ICON = typeof ICON;
export type AN_ICON = ICON[keyof ICON];
